### ISSUE TITLE
Tracking issue for planned breaking changes:

### ISSUE THREAD

**Issue by sosthene-nitrokey** [japaric/heapless#494]
- [x] Rework re-exports in lib.rs https://github.com/rust-embedded/heapless/pull/490#issuecomment-2200015830
- [x] Rename `Deque::storage_len` to `len`: https://github.com/rust-embedded/heapless/pull/490#issue-2383361459
- [x] Remove the `Storage` generic on `history_buf::OldestOrdered`. The view version can become the version that is always used: https://github.com/rust-embedded/heapless/pull/570
- [x] `Queue::capacity` and `Queue::storage_capacity` should be changed
- [x] `spsc`: The iterators, consumers and producers should be made to only have the `View` variants: https://github.com/rust-embedded/heapless/pull/571
- [x] `SortedLinkLinst`: `Iter` and `FindMut` should be made to only exist in the `View` version: https://github.com/rust-embedded/heapless/pull/540
- [x] `Vec`: rename `storage_capacity` to `capacity` and remove the `const` version https://github.com/rust-embedded/heapless/pull/538
- [x] `SortedLinkedList` removing unit error type: #532
- [x] `Vec` and `String` removing unit error type: #533

**Comment by sgued** [comment]
This can be closed as everything is done and will be included in 0.9.1.
